"""
invoice_text_extractor.py

Extracts text (and word positions) from invoice PDFs that have a real
embedded text layer — i.e. PDFs generated by software (Tally, GST portal,
Zoho, accounting tools), as opposed to scanned/photographed paper invoices
saved as PDF.

This module does NOT handle OCR. Its job is narrower: read what's already
machine-readable, and clearly report when a PDF has no usable text so the
caller knows to route it to the OCR path instead (built in a later step).
"""

import pdfplumber
from dataclasses import dataclass, field


@dataclass
class WordBox:
    """
    A single word found on the page, with its position.
    Position is in points, measured from the top-left of the page —
    this is what we'll need later to draw/correct bounding boxes.
    """
    text: str
    x0: float
    x1: float
    top: float
    bottom: float


@dataclass
class PageExtractionResult:
    page_number: int
    full_text: str
    words: list[WordBox] = field(default_factory=list)


@dataclass
class PdfExtractionResult:
    success: bool
    has_usable_text: bool
    pages: list[PageExtractionResult] = field(default_factory=list)
    error_message: str = ""

    @property
    def full_text(self) -> str:
        """Convenience: all pages' text joined together."""
        return "\n".join(page.full_text for page in self.pages)


# A PDF page with fewer than this many characters of extracted text is
# treated as having no usable text layer (likely a scanned image PDF).
# This threshold is a heuristic, not a guarantee — we may need to tune
# it once we see more real-world samples.
MIN_CHARACTERS_FOR_USABLE_TEXT = 20


def extract_text_from_pdf(pdf_path: str) -> PdfExtractionResult:
    """
    Attempts to extract embedded text (and word positions) from every
    page of the given PDF.

    Returns has_usable_text=False if the PDF appears to have no real
    text layer (e.g. it's a scanned image), so the caller can route it
    to OCR instead, rather than silently returning near-empty results.
    """
    try:
        pages_result: list[PageExtractionResult] = []

        with pdfplumber.open(pdf_path) as pdf:
            for page_index, page in enumerate(pdf.pages, start=1):
                full_text = page.extract_text() or ""

                raw_words = page.extract_words() or []
                words = [
                    WordBox(
                        text=w["text"],
                        x0=w["x0"],
                        x1=w["x1"],
                        top=w["top"],
                        bottom=w["bottom"],
                    )
                    for w in raw_words
                ]

                pages_result.append(
                    PageExtractionResult(
                        page_number=page_index,
                        full_text=full_text,
                        words=words,
                    )
                )

    except Exception as e:
        # pdfplumber/pdfminer can raise various exception types on
        # corrupt or unusual PDFs — we deliberately catch broadly here
        # and report it cleanly rather than crashing the app.
        return PdfExtractionResult(
            success=False,
            has_usable_text=False,
            error_message=f"Could not read PDF: {e}",
        )

    total_characters = sum(len(page.full_text.strip()) for page in pages_result)
    has_usable_text = total_characters >= MIN_CHARACTERS_FOR_USABLE_TEXT

    return PdfExtractionResult(
        success=True,
        has_usable_text=has_usable_text,
        pages=pages_result,
    )